dataset:
  database:
    backend:
      type: none
    cache:
      path: memory
      sources:
        - type: local
          path: sandbox/tests/datasets/samples
  max_runner_concurrency: 3
  default_dataset_table: code_eval_${dataset_id}
  registry:
    - module_path: sandbox.datasets.autoeval
      class_name: AutoEvalDataset
    - module_path: sandbox.datasets.common_oj
      class_name: CommonOJDataset
sandbox:
  isolation: lite
  cleanup_process: false
  restore_bash: false
  max_concurrency: 0  # concurrency in ci is limited by pytest-xdist
common:
  logging_color: true
